apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-service-subscription
  namespace: microservices
spec:
  topic: orders-events
  route: /product-updates
  pubsubname: orders-pubsub
scopes:
- orderservice