apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.dapr.io
spec:
  group: dapr.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              topic:
                type: string
              route:
                type: string
              pubsubname:
                type: string
          scopes:
            type: array
            items:
              type: string
  scope: Namespaced
  names:
    plural: subscriptions
    singular: subscription
    kind: Subscription